from random import randint
print('Defina seu Nome Para Jogar:')
nome = input('> ')
while True:
    x2 = randint(1, 3)
    print('Pedra Papel ou Tesoura')
    print('')
    print('[1] Pedra')
    print('[2] Papel')
    print('[3] Tesoura')
    print('')
    x1 = int(input('> '))
    if x1 == 1:
        if x2 == 1:
            print(f'{nome}: Pedra')
            print('Computador: Pedra')
            print('')
            print('Pedra x Pedra')
            print('Empate')
            print('')
            print('Clique na Tecla [Enter] para Continuar')
            input('> ')
        elif x2 == 2:
            print(f'{nome}: Pedra')
            print('Computador: Papel')
            print('')
            print('Pedra x Papel')
            print('Derrota')
            print('')
            print('Clique na Tecla [Enter] para Continuar')
            input('> ')
        elif x2 == 3:
            print(f'{nome}: Pedra')
            print('Computador: Tesoura')
            print('')
            print('Pedra x Tesoura')
            print('Vitoria')
            print('')
            print('Clique na Tecla [Enter] para Continuar')
            input('> ')
    elif x1 == 2:
        if x2 == 1:
            print(f'{nome}: Papel')
            print('Computador: Pedra')
            print('')
            print('Papel x Pedra')
            print('Vitoria')
            print('')
            print('Clique na Tecla [Enter] para Continuar')
            input('> ')
        elif x2 == 2:
            print(f'{nome}: Papel')
            print('Computador: Papel')
            print('')
            print('Papel x Papel')
            print('Empate')
            print('')
            print('Clique na Tecla [Enter] para Continuar')
            input('> ')
        elif x2 == 3:
            print(f'{nome}: Papel')
            print('Computador: Tesoura')
            print('')
            print('Papel x Tesoura')
            print('Derrota')
            print('')
            print('Clique na Tecla [Enter] para Continuar')
            input('> ')
    elif x1 == 3:
        if x2 == 1:
            print(f'{nome}: Tesoura')
            print('Computador: Pedra')
            print('')
            print('Tesoura x Pedra')
            print('Derrota')
            print('')
            print('Clique na Tecla [Enter] para Continuar')
            input('> ')
        elif x2 == 2:
            print(f'{nome}: Tesoura')
            print('Computador: Papel')
            print('')
            print('Tesoura x Papel')
            print('Vitoria')
            print('')
            print('Clique na Tecla [Enter] para Continuar')
            input('> ')
        elif x2 == 3:
            print(f'{nome}: Tesoura')
            print('Computador: Tesoura')
            print('')
            print('Tesoura x Tesoura')
            print('Empate')
            print('')
            print('Clique na Tecla [Enter] para Continuar')
            input('> ')
